### ISSUE TITLE
RuntimeException: you should enable MustachePlugin in play.plugins

### ISSUE THREAD

**Issue by mfirry** [julienba/play2-mustache#6]
play.core.ActionInvoker$$anonfun$receive$1$$anon$1: Execution exception [[RuntimeException: you should enable MustachePlugin in play.plugins]]
    at play.core.ActionInvoker$$anonfun$receive$1.apply(Invoker.scala:134) [play_2.9.1-2.0.4.jar:2.0.4]
    at play.core.ActionInvoker$$anonfun$receive$1.apply(Invoker.scala:115) [play_2.9.1-2.0.4.jar:2.0.4]
    at akka.actor.Actor$class.apply(Actor.scala:318) [akka-actor.jar:2.0.2]
    at play.core.ActionInvoker.apply(Invoker.scala:113) [play_2.9.1-2.0.4.jar:2.0.4]
    at akka.actor.ActorCell.invoke(ActorCell.scala:626) [akka-actor.jar:2.0.2]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:197) [akka-actor.jar:2.0.2]
Caused by: java.lang.RuntimeException: you should enable MustachePlugin in play.plugins
    at org.jba.Mustache$$anonfun$plugin$1$$anonfun$apply$1.apply(Mustache.scala:92) ~[play2-mustache_2.9.1-1.0.0.jar:1.0.0]
    at org.jba.Mustache$$anonfun$plugin$1$$anonfun$apply$1.apply(Mustache.scala:92) ~[play2-mustache_2.9.1-1.0.0.jar:1.0.0]
    at scala.Option.getOrElse(Option.scala:108) ~[scala-library.jar:0.11.3]
    at org.jba.Mustache$$anonfun$plugin$1.apply(Mustache.scala:92) ~[play2-mustache_2.9.1-1.0.0.jar:1.0.0]
    at org.jba.Mustache$$anonfun$plugin$1.apply(Mustache.scala:91) ~[play2-mustache_2.9.1-1.0.0.jar:1.0.0]
    at scala.Option.map(Option.scala:133) ~[scala-library.jar:0.11.3]

**Comment by julienba** [comment]
Do you have enable the plugin ?

**Comment by mfirry** [comment]
i have put this inside the Build.scala

templatesImport += "org.jba.Mustache"

not enough?

**Comment by julienba** [comment]
this lines import org.jba.Mustache in all templates. 
For add a plugin you need to create a file conf/play.plugins with the order of loading and the plugin name. You can see en example here: https://github.com/julienba/play2-mustache/blob/master/sample/conf/play.plugins

**Comment by mfirry** [comment]
great thanks
